#! /usr/bin/python3
# -*- coding utf-8 -*-
# (c) 2025 Fomenko A V


import os
import shutil
import argparse
import configparser
from datetime import *
from os.path import join, isfile, splitext

from pymediainfo import MediaInfo

try:
    import exifread
except Exception as e:
    print("{}\nInstall module 'exifread', use 'pip install exifread'".format(e))
    exit()

CONFIG_DIR = join(os.environ['HOME'], ".config/photosort")
CONFIG_FILE = join(os.environ['HOME'], ".config/photosort/config.conf")


def check_config_file():
    if isfile(CONFIG_FILE):
        return True

    config = configparser.ConfigParser()
    config['Main'] = {"path_to_save": join(os.environ['HOME'], "Photo")}

    os.makedirs(CONFIG_DIR, exist_ok=True)
    with open(CONFIG_FILE, 'w') as configfile:
        config.write(configfile)

    print("Default config are create now!")
    ans = input("Continue? (y/n)\n")

    if ans.lower() == 'y':
        return True

    return False


def read_conf():
    config = configparser.ConfigParser()
    config.read(CONFIG_FILE)
    return config["Main"].get('path_to_save')


def argparse_mm():
    p = argparse.ArgumentParser(description="photosort help page")

    p.add_argument("--copy", dest="copy",
                   action='store_true', help='Copy photos')
    p.add_argument("--move", dest="move", action='store_true',
                   help='Move photosort')

    return p.parse_args()


def main():
    # check config file, if not exist it will create at startup
    if not check_config_file():
        return

    args = argparse_mm()

    # absolute path to src image folder
    fPath = os.curdir

    # absolute path to Photo storage folder
    pht = join(read_conf(), '{}/{} {}')

    # counter
    i = 0

    # from str to DateTime parse patterns
    patern = "%Y:%m:%d %H:%M:%S"
    patern2 = "%Y-%m-%d %H:%M:%S UTC "  # 2023-08-26 09:13:38 UTC
    jpeg_mime = [".jpg", ".jfif", ".jpe", ".jpeg"]
    mp4_mime = [".mp4"]

    # iteration of all files in src folder
    for f in os.listdir(fPath):
        # absolute path to file

        file_path = join(fPath, f)

        if isfile(file_path) and splitext(file_path)[-1].lower() in jpeg_mime:
            # IMG files
            try:
                # EXIF tags
                tags_EXIF = {}

                # reading EXIF tags
                with open(file_path, 'rb') as img_file:
                    tags_EXIF = exifread.process_file(img_file)

                # parse date from EXIF info
                s = str(tags_EXIF.get("Image DateTime"))
                d = datetime.strptime(s, patern)
            except:
                pass

        if isfile(file_path) and splitext(file_path)[-1].lower() in mp4_mime:
            # Video files
            try:
                mediainfo = MediaInfo.parse(file_path)
                d = datetime.strptime(mediainfo.tracks[0].tagged_date, patern2)
            except:
                pass

        try:
            full_path = pht.format(d.year, d.month, datetime.strftime(d, "%B"))
        except:
            pass
        else:
            os.makedirs(full_path, exist_ok=True)

            if args.move:
                try:
                    shutil.move(file_path, full_path)
                    print("File {} are moved".format(f))
                    i += 1
                except Exception as e:
                    print("File {} are not moved. {}".format(f, e))
            elif args.copy:
                try:
                    shutil.copy(file_path, full_path)
                    print("File {} are copied".format(f))
                    i += 1
                except Exception as e:
                    print("File {} are not copied. {}".format(f, e))
            else:
                print("Bad usage. Use '--copy' or '-move' option")
                return       

        d = None

    print(i)
    return(0)


if __name__ == '__main__':
    main()
